
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aditcam
 */
public class Organization_hireRes extends javax.swing.JFrame {
    String compID;
    String BID;
    String depID;
    int hired;
    String start;
    String end;

    /**
     * Creates new form Organization_hireRes
     */
    public Organization_hireRes() {
        initComponents();
        this.setLocationRelativeTo(null);
        displayAll();   
    }
    
     public Organization_hireRes(String c_id,String b_id,String dep_id,String startd,String endd)
    {
        initComponents();
        hired = 0;
        compID = c_id;
        BID = b_id;
        depID = dep_id;
        start = startd;
        end = endd;
        this.setLocationRelativeTo(null);
        displayAll();   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Hire = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        quit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Query results");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Enter Ids of employees and press Enter to hire:");

        Hire.setText("Hire");
        Hire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HireActionPerformed(evt);
            }
        });

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        ta1.setLineWrap(true);
        ta1.setRows(5);
        jScrollPane2.setViewportView(ta1);

        quit.setText("Exit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 188, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hire)
                .addGap(260, 260, 260)
                .addComponent(quit)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quit)
                    .addComponent(Hire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HireActionPerformed
        String id_emp = IdField.getText();
        IdField.setText("");
        String query = "insert into works values('" + id_emp + "','" + compID + "','" + BID + "','"  + depID + "')";
        String upQ = "update employee set avl = 'N' where ID = '" + id_emp + "'";
        String upQ2 = "update dep set no_avl = no_avl - 1 where dept_ID = '" + depID + "'";
        if(ta1.getText().equals("               ID              NAME              H_DEG              SKILL"))
        {
            JOptionPane.showMessageDialog(this,"No More employees available");
        }
        else if(!(ta1.getText().contains(id_emp)))
        {
             JOptionPane.showMessageDialog(this,"Enter a valid id ");
        }
        else{

        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            //step2 create  the connection object
            Connection con=DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe","system","curio");

            //step3 create the statement object
            Statement stmt=con.createStatement();
            //step4 execute query
            ResultSet os=stmt.executeQuery(query);
            stmt.executeUpdate(upQ);
            stmt.executeUpdate(upQ2);
            hired++;
            con.close();
        }

        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Enter a valid sql command"+e.toString());
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this," "+e.toString());
        }
        displayAll();
        }
    }//GEN-LAST:event_HireActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed

        String query = "insert into hires values('" + compID + "','" + BID + "','" +depID+ "','"  + hired + "','" +start+ "','" + end + "')" ;

        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            //step2 create  the connection object
            Connection con=DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe","system","happy123");

            //step3 create the statement object
            Statement stmt=con.createStatement();
            //step4 execute query
            ResultSet os=stmt.executeQuery(query);

            con.close();
        }

        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Enter a valid sql command"+e.toString());
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this," "+e.toString());
        }
        this.setVisible(false);
        new Organization_option().setVisible(true);
    }//GEN-LAST:event_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Organization_hireRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Organization_hireRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Organization_hireRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Organization_hireRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Organization_hireRes().setVisible(true);
            }
        });
    }
      public void displayAll()
    {
      ta1.setText("");
      String query = "select ID,name,H_deg,skill from employee where dept_ID = '" + depID + "'" + "and avl = 'Y'";
      System.out.println(query);
        
      try
       {
     Class.forName("oracle.jdbc.driver.OracleDriver");  
  
    //step2 create  the connection object  
    Connection con=DriverManager.getConnection(  
    "jdbc:oracle:thin:@localhost:1521:xe","system","happy123");  
  
    //step3 create the statement object  
    Statement stmt=con.createStatement();  
    //step4 execute query  
    ResultSet os=stmt.executeQuery(query); 
  
    ResultSetMetaData rsMetaData = os.getMetaData();
    String col_list= " ";
    int col = rsMetaData.getColumnCount();
    for(int i=1; i<col+1;i++)
    {
        String col_Name = rsMetaData.getColumnName(i);
        col_list+="              "+col_Name;
    } 
    ta1.append(col_list);
    
    while(os.next())
    {
        String temp = "";
      
        System.out.print(temp);
        for(int j=1;j<col+1;j++)
        {   
            temp += "            || " + os.getString(j);
        }
        ta1.append("\n");
        ta1.append(temp);

    }

    con.close();  
       }
        
         catch(SQLException e)
         {
    JOptionPane.showMessageDialog(this,"Enter a valid sql command"+e.toString());
         }  
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(this," "+e.toString());
       }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hire;
    private javax.swing.JTextField IdField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton quit;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
